runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10
# [START configuration]
endpoints_api_service:
# The following values are to be replaced by information from the output of
# 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  name: subtle-seer-267419.appspot.com
#rollout_strategy: managed 
# Copyright 2015-2016, Google, 
  config_id: 2020-02-07r0  # este config_id se cambia de acuerdo a la fecha actual 
# [END configuration]
